export const enum HttpStatusCodes {
    HTTP_OK = 200,
    HTTP_CREATED = 201,
    HTTP_MULTIPLE_CHOICES = 300,
    HTTP_FOUND = 302,
    HTTP_VALIDATION_ERROR = 422,
    HTTP_INTERNAL_SERVER_ERROR = 500,
    HTTP_PERMISSION_ERROR = 403,
    HTTP_NOT_FOUND = 404,
    HTTP_BAD_REQUEST = 400,
  }